# This file defines the requirements for a productive project deployment.
# It should not contain dependencies for tests, developer tools, etc. (see environment-dev.yml)
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10.*{% if cookiecutter.config_file == 'hocon' %}
  - pyhocon=0.3.*{% elif cookiecutter.config_file == 'yaml' %}
  - PyYAML=6.*{% endif %}{% if cookiecutter.create_cli == 'yes' %}
  - pip
  - pip:
      - typer~=0.7.0{% endif %}
