name: at-python-template
channels:
  - conda-forge
  - defaults
dependencies:
  # no python version specified here, we use different versions in the CI pipeline
  - pytest=7.*
  - pytest-mock=3.*
  - cookiecutter=2.*
  - pyhocon=0.3.*
  - PyYAML=6.*
  - pip
  - pip:
      - typer~=0.7.0
